site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  font: false #Deaktiviert um Konflikt mit extra.css zu vermeiden
  features:
    - navigation.footer
  icon:
    logo: material/account-school-outline
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  

# Emojis ans Icons
markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Extension for code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  # Admonition
  - admonition
  - pymdownx.details
  # Katex
  - pymdownx.arithmatex:
      generic: true
  # Images
  - md_in_html
  - pymdownx.blocks.caption

copyright: Copyright &copy; 2026  Dr. Willi Paufler


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
