site_name: QR - Summe
site_url: https://qr-summe.de
theme:
  name: material
  language: de
  font: false #Deaktiviert um Konflikt mit extra.css zu vermeiden
  icon:
    logo: material/account-school-outline
  palette:
    # 1. Automatische Systemerkennung (wählt je nach OS-Einstellung)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Zum hellen Modus wechseln
      primary: blue
      accent: orange

    # 2. Light Mode (wird aktiv, wenn der User explizit "hell" erzwingt)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Zum dunklen Modus wechseln
      primary: blue
      accent: orange

    # 3. Dark Mode (wird aktiv, wenn der User explizit "dunkel" erzwingt)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Zu Systemeinstellungen wechseln
      primary: green
      accent: orange
  

# Emojis ans Icons
markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Extension for code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  # Admonition
  - admonition
  - pymdownx.details
  # Katex
  - pymdownx.arithmatex:
      generic: true
  # Images
  - md_in_html
  - pymdownx.blocks.caption



copyright: Copyright &copy; 2026  Dr. Willi Paufler


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css



nav:
  - 🏫 Home: index.md
  - 📘 Mathe Sek I:
      - Potenzfunktionen: ma_sek_i/potenzfunktion/index.md
      # Die Tipps und Lösungen werden hier einfach nicht erwähnt.
  - 📗 Mathe Sek II:
      - Differentialrechnung:
        - 1. Grundlagen Funktionen: ma_sek_ii/diff/basic/index.md
        - 2. Ableitungen: ma_sek_ii/diff/abl/index.md
        - 3. Tangenten, Normalen & Winkel: ma_sek_ii/diff/tnw/index.md
        - 4. Kurvendiskussion: ma_sek_ii/diff/kd/index.md
        - 5. Extremwertprobleme: ma_sek_ii/diff/ewp/index.md
        - 6. Rekonstruktion: ma_sek_ii/diff/rek/index.md
      - Integralrechnung:
        - 1. Bestimmtes und unbestimmtes Integral: ma_sek_ii/int/basic/index.md
        - 2. Flächenberechnung: ma_sek_ii/int/flaeche/index.md
        - 3. Volumenberechnung: ma_sek_ii/int/vol/index.md
        - 4. Rekonstruktion von Beständen: ma_sek_ii/int/rek/index.md
      - Vektorrechnung:
        - 1. Punkte und Vektoren: ma_sek_ii/vek/basic/index.md
